spring:
  application:
    name: SimpleBibleAPI
  # apenas para demonstração,
  # os versículos poderiam ser armazenados de outra formA
  datasource:
    url: jdbc:h2:mem:BibleDb
    username: user
    password: passd